name: Android Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Purane Setup Gradle ko hata kar ye simple script use karein
      - name: Force Install Gradle and Wrapper
        run: |
          sudo apt-get install gradle -y
          gradle wrapper
          chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VMAX-Sniper-VIP-APK
          path: app/build/outputs/apk/debug/*.apk
